 services:
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
    - "5433:5432"
    volumes:
    - ./pgdata/data:/var/lib/postgresql/data
    env_file:
    - docker.env
    networks:
    - postgres
 networks:
  postgres:
    driver: bridge